### ISSUE TITLE
can hubble be installed without cilium?

### ISSUE THREAD

**Issue by YogevMaty** [cilium/hubble#1192]
In past versions hubble had his own helm chart. How can I install only hubble using the new helm chart without installing the full cilium suite?

**Comment by rolinh** [comment]
Hubble is tightly coupled with Cilium and cannot be installed independently. Since Cilium v1.8, Hubble server instances are embedded in the Cilium agent. Therefore, it is not possible to run Hubble without running Cilium. It's probably possible to run Hubble with Cilium in CNI-chaining mode if the question arises because you cannot change your CNI for Cilium but this is not a setup I have attempted.
