### ISSUE TITLE
--follow doesn't work with --dict

### ISSUE THREAD

**Issue by glibsm** [cilium/hubble#121]
`hubble observe --follow --dict` should follow in dictionary mode, yet it incorrectly defaults to compact.

`--follow --json` works correctly and follows in json

**Comment by Rolinh** [comment]
Since we're talking about output formatting here, what about having a `-o, --output=` switch which would take values `compact|dict|json|...` instead? I think it would make it easier to see all available output options for the `observe` command.

I can give it a shot and fix this bug at the same time if you're up for it.
