### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by glibsm** [cilium/hubble#242]
There is currently no checklist before releasing a new version, which is error-prone.

Cilium release docs for reference: https://docs.cilium.io/en/latest/contributing/release/stable

**Comment by gandro** [comment]
Related: It would also make sense to upload docker images of released versions to `docker.io/cilium/hubble` as part of the release process.

Currently, we only have the images on quay, but other images (like `hubble-relay`) will be on hub.docker.com as they are part of the Cilium release process.

**Comment by Rolinh** [comment]
The release process is documented since #281 landed.

@gandro How should we tackle uploading docker images to dockerhub?

**Comment by gandro** [comment]
> @gandro How should we tackle uploading docker images to dockerhub?

I don't think my above comment regarding the docker image on release relevant anymore: We have a quay autobuilder with automatic tags for the `hubble` container: https://quay.io/repository/cilium/hubble?tag=latest&tab=tags

We have https://github.com/cilium/hubble/issues/361 to track the docker hub autobuilder. Let's close this issue here that we the process documented.
