### ISSUE TITLE
GetFlows/hubble observe doesn't support both --since and --follow at the same time

### ISSUE THREAD

**Issue by genbit** [cilium/hubble#363]
I'm using hubble observe as an example, however I believe it's a problem inside GetFlows implementation, and not on a client, since hubble-ui experiencing similar issue with GetFlows API.

Currently, it's not possible to do the following command:

```
hubble observe --since=1m --follow
```

Expected behavior for this command would be to first return last 1m of data from buffer, than continue streaming flows to the client. However, this is not happening, it's only streaming new flows.

Compare this with --last behavior:

```
hubble observe --last=1000 --follow
```

That command returns last 1000 flows, than continues streaming new flows. 

hubble-ui's use case for having both --follow and --since=1m is simple: we want to show user a service map, based on the last X minutes of buffered flows, instead of showing them an empty screen and making them wait for new flows to arrive.

**Comment by Rolinh** [comment]
This happens because when specifying only `--since`, then `--until` is inferred as _now_. to to create a time range. And a time range is not compatible with `--follow` (see [this](https://github.com/cilium/cilium/blob/745a26b2ead09e689f8626413467d4083a7fa00a/pkg/hubble/observer/local_observer.go#L334)).

I think this behavior could be improved:  when `--since` is provided alongside `--follow`, don't infer a default time range. This would also work if `--until` is also provided assuming that it is set sometime in the future. So basically, if `--follow` is provided alongside `--since`, one should not infer `--until`.

**Comment by genbit** [comment]
btw, I'm not observing this when run cilium from master:

```
kubectl exec -n kube-system -t ds/cilium -- hubble version               
hubble v0.7.0-dev@HEAD-186fa10 compiled with go1.14.4 on linux/amd64
```
and run Hubble CLI from within cilium pod (on Minikube), without hubble-relay.
