### ISSUE TITLE
hubble observe: support reading from json file

### ISSUE THREAD

**Issue by michi-covalent** [cilium/hubble#523]
say i have the output of `hubble observe -o jsonpb` saved to a file. it would be handy if i can pass the file to `hubble observe` later and somehow apply filters instead of trying to come up with equivalent `jq` queries.

**Comment by gandro** [comment]
This is pretty cool idea! I think it's probably a `good-second-issue` for someone already a bit familiar with the Hubble source. We should be able to reuse most of the filter code we have on the server side (except the `--since` and `--last` filters):

https://github.com/cilium/cilium/blob/3c590925362bbf863e66b20e501eeaf08c0fda84/pkg/hubble/filters/filters.go#L31-L35

What's needed is to create `v1.Event` types from the `jsonpb`, create a `FlowFilter` from the command-line arguments (via [`observe_filter.go`](https://github.com/cilium/hubble/blob/14e6aea728393750e0fff695a2803ee07b192f74/cmd/observe/observe_filter.go)), and then pass it into the above `Apply`
