### ISSUE TITLE
"cilium hubble enable" install only hubble-relay

### ISSUE THREAD

**Issue by tjrone** [cilium/hubble#703]
Why only hubble-relay is installed, but no daemonset?

Also, how to expose metrics of my existing hubble?

**Comment by kaworu** [comment]
> Why only hubble-relay is installed, but no daemonset?

The Hubble server is now provided by the Cilium agent, so there is no need for a Hubble daemonset anymore (see [this PR](https://github.com/cilium/cilium/pull/10860)). When `cilium hubble enable` is invoked, the cilium ConfigMap is patched in order to enable hubble and the cilium Pods are restarted. Additionally, Hubble Relay is installed to act as an entry point for Hubble CLI and Hubble UI requests (which can be installed as well by providing the `--ui` flag).

> Also, how to expose metrics of my existing hubble?

See [the Hubble metrics documentation](https://docs.cilium.io/en/stable/operations/metrics/#hubble-metrics). Note that this require using the Helm installation method, as enabling metrics is not currently supported by the cilium cli installation method (work is on the way to address this, see [this PR](https://github.com/cilium/cilium-cli/pull/778)).

**Comment by tjrone** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by tjrone** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
